<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-H7D89UKD" failures="0" tests="2" name="Error Validations Test" time="0.225" errors="0" timestamp="16 Jun 2023 18:47:22 GMT">
  <testcase classname="rahulshettyacademy.TestComponents.BaseTest" name="@BeforeMethod launchApplication" time="0.029">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rahulshettyacademy.TestComponents.BaseTest.initializeDriver(BaseTest.java:71)
at rahulshettyacademy.TestComponents.BaseTest.launchApplication(BaseTest.java:109)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod launchApplication -->
  <testcase classname="rahulshettyacademy.TestComponents.BaseTest" name="@AfterMethod tearDown" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rahulshettyacademy.TestComponents.BaseTest.tearDown(BaseTest.java:121)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="rahulshettyacademy.TestComponents.BaseTest" name="@BeforeMethod launchApplication" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rahulshettyacademy.TestComponents.BaseTest.initializeDriver(BaseTest.java:71)
at rahulshettyacademy.TestComponents.BaseTest.launchApplication(BaseTest.java:109)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod launchApplication -->
  <testcase classname="rahulshettyacademy.TestComponents.BaseTest" name="@AfterMethod tearDown" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rahulshettyacademy.TestComponents.BaseTest.tearDown(BaseTest.java:121)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.0">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="ProductErrorValidation" time="0.0">
    <skipped/>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validations Test -->
